TOPDIR ?= ../..
include $(TOPDIR)/.config

$(HOME_ASSISTANT_MQTT_SUPPORT)_SRC += services/home-assistant-mqtt/home-assistant-mqtt.c
$(HOME_ASSISTANT_MQTT_SUPPORT)_ECMD_SRC += services/home-assistant-mqtt/ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
