TOPDIR ?= ../..
include $(TOPDIR)/.config

$(ALARM_PUSH_SUPPORT)_SRC += services/alarm-push/alarm-push.c
$(ALARM_PUSH_SUPPORT)_ECMD_SRC += services/alarm-push/ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
